package com.ivoid.bj;

enum Action
{
	STAND, HIT, DOUBLEDOWN, SPLIT, SURRENDER, INSURANCE_YES, INSURANCE_NO, CLEAR, REBET, DEAL, ALL, ONE, TEN, FIFTY, ONEHUNDRED, FIVEHUNDRED, ONETHOUSAND, BONUS, CHECK, COMPETITION;
}
